// GENERATED by scripts/mollib.mjs — do not edit by hand; its header says where each entry comes from.
// The Molecule tile's built-in library: 3D coordinates (an SDF molblock) and per-atom partial
// charges, in atom order. `method` says how each entry's charges were come by.

export interface MolLibraryEntry {
  key: string
  name: string
  formula: string
  aliases: string[]
  sdf: string
  charges: number[]
  method: string
}

export const MOL_LIBRARY: MolLibraryEntry[] = [
  {
    "key": "h2",
    "name": "Hydrogen",
    "formula": "H₂",
    "aliases": [
      "hydrogen",
      "dihydrogen"
    ],
    "sdf": "hydrogen\n  deck scripts/mollib.mjs\n\n  2  1  0  0  0  0  0  0  0  0999 V2000\n   -0.3707    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.3707    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      0,
      0
    ],
    "method": "a homonuclear bond shares its electrons evenly: no partial charges (bond length 0.741 Å, experimental)"
  },
  {
    "key": "o2",
    "name": "Oxygen",
    "formula": "O₂",
    "aliases": [
      "oxygen",
      "dioxygen"
    ],
    "sdf": "oxygen\n  PubChem CID 977, 3D conformer\n\n  2  1  0     0  0  0  0  0  0999 V2000\n   -0.6160    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    0.6160    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  2  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      0,
      0
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 977)"
  },
  {
    "key": "n2",
    "name": "Nitrogen",
    "formula": "N₂",
    "aliases": [
      "nitrogen",
      "dinitrogen"
    ],
    "sdf": "nitrogen\n  PubChem CID 947, 3D conformer\n\n  2  1  0     0  0  0  0  0  0999 V2000\n   -0.5560    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    0.5560    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  3  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      0,
      0
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 947)"
  },
  {
    "key": "water",
    "name": "Water",
    "formula": "H₂O",
    "aliases": [
      "h2o"
    ],
    "sdf": "water\n  PubChem CID 962, 3D conformer\n\n  3  2  0     0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    0.2774    0.8929    0.2544 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.6068   -0.2383   -0.7169 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\n  1  3  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.86,
      0.43,
      0.43
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 962)"
  },
  {
    "key": "methane",
    "name": "Methane",
    "formula": "CH₄",
    "aliases": [
      "ch4"
    ],
    "sdf": "methane\n  PubChem CID 297, 3D conformer\n\n  5  4  0     0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.5541    0.7996    0.4965 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.6833   -0.8134   -0.2536 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.7782   -0.3735    0.6692 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.4593    0.3874   -0.9121 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\n  1  3  1  0  0  0  0\n  1  4  1  0  0  0  0\n  1  5  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      0,
      0,
      0,
      0,
      0
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 297)"
  },
  {
    "key": "ammonia",
    "name": "Ammonia",
    "formula": "NH₃",
    "aliases": [
      "nh3"
    ],
    "sdf": "ammonia\n  PubChem CID 222, 3D conformer\n\n  4  3  0     0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.4417    0.2906    0.8711 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.7256    0.6896   -0.1907 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.4875   -0.8701    0.2089 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\n  1  3  1  0  0  0  0\n  1  4  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -1.08,
      0.36,
      0.36,
      0.36
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 222)"
  },
  {
    "key": "co2",
    "name": "Carbon dioxide",
    "formula": "CO₂",
    "aliases": [
      "carbon dioxide",
      "carbon-dioxide"
    ],
    "sdf": "carbon dioxide\n  PubChem CID 280, 3D conformer\n\n  3  2  0     0  0  0  0  0  0999 V2000\n   -1.1970    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    1.1970    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  3  2  0  0  0  0\n  2  3  2  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.78,
      -0.78,
      0.56
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 280)"
  },
  {
    "key": "nacl",
    "name": "Sodium chloride (ion pair)",
    "formula": "NaCl",
    "aliases": [
      "sodium chloride",
      "salt",
      "na+cl-"
    ],
    "sdf": "sodium chloride ion pair\n  deck scripts/mollib.mjs\n\n  2  0  0  0  0  0  0  0  0  0999 V2000\n   -1.1805    0.0000    0.0000 Na  0  0  0  0  0  0  0  0  0  0  0  0\n    1.1805    0.0000    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0\nM  CHG  2   1   1   2  -1\nM  END\n$$$$\n",
    "charges": [
      1,
      -1
    ],
    "method": "FORMAL ionic charges (the gas-phase pair really carries about ±0.8); Na–Cl 2.361 Å, experimental; no covalent bond drawn"
  },
  {
    "key": "methanol",
    "name": "Methanol",
    "formula": "CH₃OH",
    "aliases": [
      "ch3oh"
    ],
    "sdf": "methanol\n  PubChem CID 887, 3D conformer\n\n  6  5  0     0  0  0  0  0  0999 V2000\n    0.7079    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.7079    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.0732   -0.7690    0.6852 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.0731   -0.1947   -1.0113 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.0632    0.9786    0.3312 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.9936   -0.8804   -0.2980 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\n  1  6  1  0  0  0  0\n  2  3  1  0  0  0  0\n  2  4  1  0  0  0  0\n  2  5  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.68,
      0.28,
      0,
      0,
      0,
      0.4
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 887)"
  },
  {
    "key": "ethanol",
    "name": "Ethanol",
    "formula": "C₂H₅OH",
    "aliases": [
      "c2h5oh"
    ],
    "sdf": "ethanol\n  PubChem CID 702, 3D conformer\n\n  9  8  0     0  0  0  0  0  0999 V2000\n   -1.1712    0.2997    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.0463   -0.5665    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.2175    0.2668    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.0958   -1.2120    0.8819 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.0952   -1.1938   -0.8946 H   0  0  0  0  0  0  0  0  0  0  0  0\n    2.1050   -0.3720   -0.0177 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.2426    0.9307   -0.8704 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.2616    0.9052    0.8886 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.1291    0.8364    0.8099 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\n  1  9  1  0  0  0  0\n  2  3  1  0  0  0  0\n  2  4  1  0  0  0  0\n  2  5  1  0  0  0  0\n  3  6  1  0  0  0  0\n  3  7  1  0  0  0  0\n  3  8  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.68,
      0.28,
      0,
      0,
      0,
      0,
      0,
      0,
      0.4
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 702)"
  },
  {
    "key": "acetic-acid",
    "name": "Acetic acid",
    "formula": "CH₃COOH",
    "aliases": [
      "acetic acid",
      "ch3cooh",
      "acetate"
    ],
    "sdf": "acetic acid\n  PubChem CID 176, 3D conformer\n\n  8  7  0     0  0  0  0  0  0999 V2000\n   -0.3035    1.2890   -0.0002 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.9800   -0.8878   -0.0002 O   0  0  0  0  0  0  0  0  0  0  0  0\n    1.3743   -0.3516   -0.0002 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.0907   -0.0496    0.0006 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.8368    0.0570   -0.9021 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.8400    0.0676    0.8952 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.5207   -1.4356    0.0064 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.2598    1.5081   -0.0008 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  4  1  0  0  0  0\n  1  8  1  0  0  0  0\n  2  4  2  0  0  0  0\n  3  4  1  0  0  0  0\n  3  5  1  0  0  0  0\n  3  6  1  0  0  0  0\n  3  7  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.65,
      -0.57,
      0.06,
      0.66,
      0,
      0,
      0,
      0.5
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 176)"
  },
  {
    "key": "benzene",
    "name": "Benzene",
    "formula": "C₆H₆",
    "aliases": [
      "c6h6"
    ],
    "sdf": "benzene\n  PubChem CID 241, 3D conformer\n\n 12 12  0     0  0  0  0  0  0999 V2000\n   -1.2131   -0.6884    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.2028    0.7064    0.0001 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.0103   -1.3948    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0104    1.3948   -0.0001 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.2028   -0.7063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.2131    0.6884    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.1577   -1.2244    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.1393    1.2564    0.0001 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.0184   -2.4809   -0.0001 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0184    2.4808    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    2.1394   -1.2563    0.0001 H   0  0  0  0  0  0  0  0  0  0  0  0\n    2.1577    1.2245    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  2  0  0  0  0\n  1  3  1  0  0  0  0\n  1  7  1  0  0  0  0\n  2  4  1  0  0  0  0\n  2  8  1  0  0  0  0\n  3  5  2  0  0  0  0\n  3  9  1  0  0  0  0\n  4  6  2  0  0  0  0\n  4 10  1  0  0  0  0\n  5  6  1  0  0  0  0\n  5 11  1  0  0  0  0\n  6 12  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.15,
      -0.15,
      -0.15,
      -0.15,
      -0.15,
      -0.15,
      0.15,
      0.15,
      0.15,
      0.15,
      0.15,
      0.15
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 241)"
  },
  {
    "key": "water-dimer",
    "name": "Water dimer (hydrogen-bonded)",
    "formula": "(H₂O)₂",
    "aliases": [
      "water dimer",
      "h2o-dimer",
      "waters"
    ],
    "sdf": "water dimer\n  deck scripts/mollib.mjs\n\n  6  4  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    0.9572    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.2400    0.0000   -0.9266 H   0  0  0  0  0  0  0  0  0  0  0  0\n    2.9800    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    3.2991    0.7570    0.4914 H   0  0  0  0  0  0  0  0  0  0  0  0\n    3.2991   -0.7570    0.4914 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\n  1  3  1  0  0  0  0\n  4  5  1  0  0  0  0\n  4  6  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.86,
      0.43,
      0.43,
      -0.86,
      0.43,
      0.43
    ],
    "method": "water’s MMFF94 charges on each monomer; geometry by hand: experimental monomers, O···O 2.98 Å, a linear O–H···O, the acceptor tilted 57°"
  },
  {
    "key": "glycine",
    "name": "Glycine",
    "formula": "C₂H₅NO₂",
    "aliases": [
      "gly"
    ],
    "sdf": "glycine\n  PubChem CID 750, 3D conformer\n\n 10  9  0     0  0  0  0  0  0999 V2000\n   -1.6487    0.6571   -0.0104 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.4837   -1.2934   -0.0005 O   0  0  0  0  0  0  0  0  0  0  0  0\n    1.9006   -0.0812   -0.0090 N   0  0  0  0  0  0  0  0  0  0  0  0\n    0.7341    0.7867    0.0079 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.5023   -0.0691    0.0120 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.7326    1.4215   -0.8824 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.7464    1.4088    0.9069 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.8743   -0.6844   -0.8301 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.8887   -0.6969    0.8031 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.4447    0.0839   -0.0260 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  5  1  0  0  0  0\n  1 10  1  0  0  0  0\n  2  5  2  0  0  0  0\n  3  4  1  0  0  0  0\n  3  8  1  0  0  0  0\n  3  9  1  0  0  0  0\n  4  5  1  0  0  0  0\n  4  6  1  0  0  0  0\n  4  7  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.65,
      -0.57,
      -0.99,
      0.33,
      0.66,
      0,
      0,
      0.36,
      0.36,
      0.5
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 750)"
  },
  {
    "key": "alanine",
    "name": "Alanine",
    "formula": "C₃H₇NO₂",
    "aliases": [
      "ala",
      "l-alanine"
    ],
    "sdf": "L-alanine\n  PubChem CID 5950, 3D conformer\n\n 13 12  0     1  0  0  0  0  0999 V2000\n    1.4573   -1.0438    0.2682 O   0  0  0  0  0  0  0  0  0  0  0  0\n    1.2492    1.1165   -0.4047 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.4105    1.1507    0.1821 N   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.7085   -0.1136    0.3937 C   0  0  1  0  0  0  0  0  0  0  0  0\n   -1.3345   -1.2000   -0.4702 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.7470    0.0903    0.0308 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.7666   -0.3737    1.4558 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.8580   -2.1695   -0.2878 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.4023   -1.3127   -0.2521 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.2248   -0.9797   -1.5384 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.3916    1.0420    0.4376 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.4071    1.3875   -0.8099 H   0  0  0  0  0  0  0  0  0  0  0  0\n    2.4062   -0.9341    0.0447 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  6  1  0  0  0  0\n  1 13  1  0  0  0  0\n  2  6  2  0  0  0  0\n  3  4  1  0  0  0  0\n  3 11  1  0  0  0  0\n  3 12  1  0  0  0  0\n  4  5  1  0  0  0  0\n  4  6  1  0  0  0  0\n  4  7  1  0  0  0  0\n  5  8  1  0  0  0  0\n  5  9  1  0  0  0  0\n  5 10  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.65,
      -0.57,
      -0.99,
      0.33,
      0,
      0.66,
      0,
      0,
      0,
      0,
      0.36,
      0.36,
      0.5
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 5950)"
  },
  {
    "key": "gly-ala",
    "name": "Gly-Ala dipeptide",
    "formula": "C₅H₁₀N₂O₃",
    "aliases": [
      "glyala",
      "glycylalanine",
      "gly-ala dipeptide",
      "dipeptide"
    ],
    "sdf": "glycylalanine\n  PubChem CID 98153, 3D conformer\n\n 20 19  0     1  0  0  0  0  0999 V2000\n   -3.0526    0.0640   -1.0564 O   0  0  0  0  0  0  0  0  0  0  0  0\n    1.7307    1.1661   -0.7430 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.2880   -1.4827    0.4147 O   0  0  0  0  0  0  0  0  0  0  0  0\n    0.1955   -0.2358    0.2961 N   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8116   -0.4381   -0.1341 N   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.9897    0.5493    0.0366 C   0  0  2  0  0  0  0  0  0  0  0  0\n   -1.2329    1.5137    1.1599 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.4648    0.1420   -0.1189 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.1476   -0.4101   -0.1587 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.5084   -0.8683    0.3040 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.8309    1.0951   -0.9009 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0915   -1.0947    0.8299 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.1321    2.1117    0.9760 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.3897    2.2012    1.2869 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.3788    0.9914    2.1126 H   0  0  0  0  0  0  0  0  0  0  0  0\n    2.2617   -1.8432   -0.1296 H   0  0  0  0  0  0  0  0  0  0  0  0\n    2.4914   -0.9562    1.3952 H   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8456   -0.4125   -1.1526 H   0  0  0  0  0  0  0  0  0  0  0  0\n    4.5121   -1.1202    0.1534 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.8047   -0.5542   -1.1776 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  9  1  0  0  0  0\n  1 20  1  0  0  0  0\n  2  8  2  0  0  0  0\n  3  9  2  0  0  0  0\n  4  6  1  0  0  0  0\n  4  8  1  0  0  0  0\n  4 12  1  0  0  0  0\n  5 10  1  0  0  0  0\n  5 18  1  0  0  0  0\n  5 19  1  0  0  0  0\n  6  7  1  0  0  0  0\n  6  9  1  0  0  0  0\n  6 11  1  0  0  0  0\n  7 13  1  0  0  0  0\n  7 14  1  0  0  0  0\n  7 15  1  0  0  0  0\n  8 10  1  0  0  0  0\n 10 16  1  0  0  0  0\n 10 17  1  0  0  0  0\nM  END\n$$$$\n",
    "charges": [
      -0.65,
      -0.57,
      -0.57,
      -0.73,
      -0.99,
      0.36,
      0,
      0.57,
      0.66,
      0.33,
      0,
      0.37,
      0,
      0,
      0,
      0,
      0,
      0.36,
      0.36,
      0.5
    ],
    "method": "MMFF94 partial charges, from PubChem’s computed 3D conformer (CID 98153)"
  }
]
